### ISSUE TITLE
Container does not start

### ISSUE THREAD

**Issue by dlednik** [jeshan/bitcore-testnet#1]
Tried to run it in aws in rancheros

```
15/02/2018 15:31:21[dumb-init] ./bitcore-node-entrypoint.sh: No such file or directory
```

**Comment by jeshan** [comment]
I tried it in a clean environment just now without issues.

You need the other files in this repo as well.
Docker Hub uses this repo to build my image, so I'm sure it's working fine.

![image](https://user-images.githubusercontent.com/1020565/36271502-39fb0072-1298-11e8-8d06-5903eb0599a2.png)

**Comment by dlednik** [comment]
image on docker hub is old then. I did not build it from source.
Can you push new build to hub pls so I can check

**Comment by jeshan** [comment]
I usually build it when I push new code but I forced a build on Docker Hub just now to make sure.

**Comment by dlednik** [comment]
still same issue. don't know why but it can't find that file. And the container keeps restarting so I can't peek into the console where the files are.

I had to use a different image from docker hub to run bitcore node

**Comment by jeshan** [comment]
OK I don't know anything about Rancher OS but I tried again by pulling the image from Docker Hub:

![image](https://user-images.githubusercontent.com/1020565/36312446-00b3226c-1348-11e8-8b44-9b2078a09e9b.png)

Just curious.. which image are you using instead?

**Comment by dlednik** [comment]
this one: https://hub.docker.com/r/sena/bitcore/

it's weird. Maybe I did not set up the volume mapping correctly and that is why it does not find the files.

looking at your print out I should have mapped `/root/bitcoin-node/data` folder instead of `/root/bitcoin-node` like it says on the docker hub?

**Comment by dlednik** [comment]
yep, issue with folder mapping. Just tried your image again with out any volume mappings and it works

```

16/02/2018 14:52:27[2018-02-16T14:52:26.979Z] info: Using config: /root/bitcoin-node/bitcore-node.json
16/02/2018 14:52:27[2018-02-16T14:52:27.001Z] info: Using network: testnet
16/02/2018 14:52:27[2018-02-16T14:52:27.002Z] info: Starting bitcoind
16/02/2018 14:52:27[2018-02-16T14:52:27.042Z] info: Using bitcoin config file: /root/bitcoin-node/data/bitcoin.conf
16/02/2018 14:52:27[2018-02-16T14:52:27.083Z] info: Starting bitcoin process
16/02/2018 14:52:32[2018-02-16T14:52:32.654Z] warn: Loading wallet...
16/02/2018 14:52:38[2018-02-16T14:52:38.207Z] info: Bitcoin Height: 78 Percentage: 0.00
16/02/2018 14:52:38[2018-02-16T14:52:38.288Z] warn: ZMQ connection delay: tcp://127.0.0.1:28332
16/02/2018 14:52:38[2018-02-16T14:52:38.289Z] info: ZMQ connected to: tcp://127.0.0.1:28332
16/02/2018 14:52:38[2018-02-16T14:52:38.374Z] info: Bitcoin Daemon Ready
16/02/2018 14:52:38[2018-02-16T14:52:38.392Z] info: Starting web
16/02/2018 14:52:39[2018-02-16T14:52:39.152Z] info: Starting insight-api
16/02/2018 14:52:39[2018-02-16T14:52:39.153Z] info: Starting insight-ui
16/02/2018 14:52:39[2018-02-16T14:52:39.174Z] info: Bitcore Node ready
16/02/2018 14:52:53[2018-02-16T14:52:53.303Z] info: Bitcoin Height: 650 Percentage: 0.06
```

Think the problem is that the folder is mapped when you run the container. At which point the whole `/root/bitcoin-node` is empty and that is why your script is missing :)

so a fix for rancher is to map data folder and config json file separately or to manually copy sh file to the folder you map it to. I did not create a volume for this and bind it to the folder. That is why it failed.

**Comment by jeshan** [comment]
Glad you found a solution!

**Comment by bush4u** [comment]
Hi @jeshan . 

Thanks for making this available. I have been making use of bitcore-lib and bitcore-insight libraries in my project, and is has not been easy for me, due to frequent outages of bitpay server connections. 
I have this image(bitcore node) now and was hoping i could get an high level highlights on how to connect to this container service endpoints, so i can be less dependent on bitpay public API. I am semi average in this field. 
Thanks.

**Comment by jeshan** [comment]
@bush4u 
Running this project as follows:
`docker run --rm -P -v /root/bitcoin-node --name testnet jeshan/bitcore-node`

gets me this container:
![image](https://user-images.githubusercontent.com/1020565/94956902-f5158f80-04fd-11eb-8c0f-cd5a07022cba.png)

Insight UI is running internally on port 3001 and is mapped to 32772 on localhost:
![image](https://user-images.githubusercontent.com/1020565/94957018-22fad400-04fe-11eb-8204-156341860f66.png)

The api is on the same port and this shows it's running (the library will of course pass in the right parameters):
![image](https://user-images.githubusercontent.com/1020565/94957400-b92efa00-04fe-11eb-804c-97661599fb26.png)


Hope that helps. Otherwise, open a new issue.

**Comment by bush4u** [comment]
Thanks so much for saving my day. 
This works perfectly well.
So grateful for your support
